name: java

services:
  backend:
    image: ${COMPOSE_PROJECT_NAME}
    build: .
    healthcheck:
      test: "wget -qO- http://localhost:8080"
      start_period: 20s
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready"
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: "rabbitmq-diagnostics check_running"
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: "wget -qO- http://nginx:80"
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres:
  rabbitmq:
