name: Production Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    environment:
      name: "production"
      url: ${{ vars.URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create application-prod.properties
        run: |
          echo "spring.profiles.active=prod" > src/main/resources/application.properties
          echo "${{ secrets.APPLICATION_PROPERTIES }}" | base64 --decode > src/main/resources/application-prod.properties
                  
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: java_prod:latest
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save and compress Docker image
        run: docker save java_prod:latest | gzip > java_prod.tar.gz
      
      - name: Copy compressed image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "java_prod.tar.gz"
          target: "/tmp"

      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/hng_boilerplate_java_web
            git add .
            git stash
            git checkout main
            git pull origin main
            gunzip -c /tmp/java_prod.tar.gz | docker load
            rm -f /tmp/java_prod.tar.gz
            docker compose -f compose.yaml -f compose/compose.prod.yaml up -d