name: PR Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy-pr:
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.preview-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v4

      - id: deploy
        name: Pull Request Deploy
        uses: hngprojects/pr-deploy@main
        run: |
          # Your deployment commands here
          # For example, if you have a command that returns the URL:
          preview_url=$(your_command_to_get_url)
          echo "preview-url=$preview_url" >> $GITHUB_ENV
          comment: true
          context: '.'
          dockerfile: 'Dockerfile'
          exposed_port: '8000'
          host_volume_path: '/var/appdata'
          container_volume_path: '/app/data'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Preview URL
        run: |
         echo "Preview URL: ${{ env.preview-url }}"
