name: PR-Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy-pr:
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.preview-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Copy .env.sample to app.props
        run: cp .env.sample ./src/main/resources/application.properties

      - id: deploy
        name: Deploy Pull Request
        uses: hngprojects/pr-deploy@main
        with:
          server_host: ${{ secrets.SSH_HOST }}
          server_username: ${{ secrets.DEV_SSH_USERNAME }}
          server_password: ${{ secrets.DEV_SSH_PASSWORD }}
          # server_port: ${{ secrets.SERVER_PORT }}
          comment: true
          context: '.'
          dockerfile: 'Dockerfile'
          exposed_port: '8080'
          # host_volume_path: '/var/'
          # container_volume_path: '/var/'          
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display Preview URL
        run: |
          echo "Preview URL: ${{ steps.deploy.outputs.preview-url }}"
